BROADCAST_IP = "0.0.0.0"
LOCALHOST_IP = "127.0.0.1"
PORT = 49657
CLIENT_ENDPOINT = "http://"..LOCALHOST_IP..":"..PORT
CLIENT_DATA_ENDPOINT = CLIENT_ENDPOINT .. "/VSCOKeys/"
CLIENT_SHUTDOWN_ENDPOINT = CLIENT_ENDPOINT .. "/Shutdown/"
CLIENT_INIT_ENDPOINT = CLIENT_ENDPOINT .. "/Init/"
AUTHENTICATION_SERVER = ""
AUTHENTICATION_SERVER_ACTION = ""
AUTHENTICATION_SERVER_ENDPOINT = AUTHENTICATION_SERVER .. AUTHENTICATION_SERVER_ACTION
AUTHENTICATION_SERVER_APPID = ""
AUTHENTICATION_SERVER_SECRET = ""
AUTHENTICATION_SERVER_VERSION = ""

-- plugin-only constants
if (_PLUGIN ~= nil) then
  SERIAL_KEY_FILENAME = "skey.key"
  SERIAL_KEY_LOCATION = _PLUGIN.path .. "/" .. SERIAL_KEY_FILENAME
  SERIAL_KEY_HASH = "[E-H][A-Z,1-9][1-9][A-Z,1-9]%-[O-T][A-Z,1-9][A-L][A-Z,1-9]%-[A-Z][A-Z,1-9][U-Z][A-Z,1-9]%-[M-Z][A-Z,1-9][J-M][A-Z,1-9]"
  SERIAL_KEY_DEFAULT = "XXXX-XXXX-XXXX-XXXX"
end

TIMEOUT_TIME = 30 -- seconds

CLIENT_WAIT_FOR_SERVER_TIME = 1 -- seconds
CLIENT_UPDATE_TIME = 0.1 -- seconds
SERVER_UPDATE_TIME = 0.1 -- seconds

AUTHENTICATION_IS_ON = false